server:
   port: 8888
spring:
   cloud: 
      config:
         server:
           git:          
             uri: https://github.com/bingliu2016/Config-Properties 
             search-paths: 
              - '*ConfigrationFiles'


# Use file system backend for configurations
#spring:
#   profiles:
#      active: native 
#   cloud: 
#      config:
#         server:           
#            native:
#               searchLocations: file:///C:/Users/bingl/git-repository/config-data         
